### ISSUE TITLE
Garbage Project

### ISSUE THREAD

**Issue by dguisti** [Random-Programming-Student/The-EncryptOre-Mine#1]
I object to this garbage project. EncryptOre 1.0 is still better!

\- Dallin

**Comment by Random-Programming-Student** [comment]
The future is now, old man.

All Hail Urgulak,
Akshansh Chauhan
________________________________

**Comment by dguisti** [comment]
mvurmzur7tu7u.wat?4~14

'x!2,qx!um2kn2jkun2.x2orp! n2.qr,2x!.2!,rwp2'x! 2y xp jv42o xv32mjuurw1~9

**Comment by dguisti** [comment]
Can you add me as a collaborator please???

**Comment by dguisti** [comment]
@Random-Programming-Student give me collaborator access, now!!!
